name: 'Build/Push'

on:
  workflow_call:
    inputs:
      meteor_version:
        required: true
        type: string
        description: Meteor version to build
      docker_registry:
        type: string
        default: ghcr.io
      docker_username:
        type: string
        description: Docker username - will be used in image tag and for authentication.
        default: jorgenvatle
      docker_push:
        type: boolean
        default: true
    secrets:
      docker_password:
        required: false
        description: Password to use when authenticating with registry

jobs:
  build:
    name: ''
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to registry
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.docker_username }}
          password: ${{ secrets.DOCKER_PASSWORD || secrets.GITHUB_TOKEN }}
          registry: ${{ inputs.docker_registry }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ inputs.docker_push }}
          tags: ${{inputs.docker_registry}}/${{ inputs.docker_username }}/meteor-base:${{ inputs.meteor_version }}
          context: ./src
          build-args: |
            METEOR_VERSION=${{ inputs.meteor_version }}


