name: 'Build/Push'

on:
  workflow_call:
    inputs:
      meteor_version:
        required: true
        type: string
        description: Meteor version to build
      meteor_tag:
        type: string
        description: Version tag to use alongside exact version (e.g. latest, alpha, beta, etc.)
        default: latest
      docker_image_name:
        type: string
        description: Docker username - will be used in image tag and for authentication.
        default: jorgenvatle/meteor-base
      docker_push:
        type: boolean
        default: true

jobs:
  image:
    name: Meteor v${{ inputs.meteor_version }}
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: jorgenvatle
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          username: jorgenvatle
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Format image
        id: image
        # language="bashsupport pro shell script"
        run: |
          imageName="$(echo $FULL_IMAGE_NAME | tr '[:upper:]' '[:lower:]')"
          tags="$imageName:${{ inputs.meteor_version }},$imageName:${{ inputs.meteor_tag }}"
          
          echo "tags=${tags}"           >> $GITHUB_OUTPUT
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ inputs.docker_push }}
          context: ./src
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            METEOR_VERSION=${{ inputs.meteor_version }}
          tags: |
            ghcr.io/${{ inputs.docker_image_name }}:${{ inputs.meteor_version }}
            ghcr.io/${{ inputs.docker_image_name }}:${{ inputs.meteor_tag || inputs.meteor_version }}
            ${{ inputs.docker_image_name }}:${{ inputs.meteor_version }}
            ${{ inputs.docker_image_name }}:${{ inputs.meteor_tag || inputs.meteor_version }}

      -
        name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        if: inputs.docker_push
        with:
          username: jorgenvatle
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: jorgenvatle/meteor-base
          short-description: >-
            A rewrite of geoffreybooth's meteor-base Docker image. Aimed at simplifying the internal process of
            building and releasing the base Docker images.

