name: 'Build/Push'

on:
  workflow_call:
    inputs:
      meteor_version:
        required: true
        type: string
        description: Meteor version to build
      meteor_tag:
        type: string
        description: Version tag to use alongside exact version (e.g. latest, alpha, beta, etc.)
        default: latest
      docker_image_name:
        type: string
        description: Docker username - will be used in image tag and for authentication.
        default: meteor-base
      docker_push:
        type: boolean
        default: true

jobs:
  image:
    name: Meteor v${{ inputs.meteor_version }}
    runs-on: ubuntu-22.04
    env:
      FULL_IMAGE_NAME: ${{ format('{0}/{1}/{2}', matrix.registry, github.repository_owner, inputs.docker_image_name) }}
    strategy:
      matrix:
        include:
          - registry: registry.hub.docker.com
            password: ${{ secrets.DOCKER_PASSWORD }}
          - registry: ghcr.io
            password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to registry
        uses: docker/login-action@v3
        with:
          username: jorgenvatle
          password: ${{ matrix.password }}
          registry: ${{ matrix.registry }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Format image
        id: image
        # language="bashsupport pro shell script"
        run: |
          imageName="$(echo $FULL_IMAGE_NAME | tr '[:upper:]' '[:lower:]')"
          tags="$imageName:${{ inputs.meteor_version }},$imageName:${{ inputs.meteor_tag }}"
          
          echo "tags=${tags}"           >> $GITHUB_OUTPUT
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ inputs.docker_push }}
          tags: ${{ steps.image.outputs.tags }}
          context: ./src
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            METEOR_VERSION=${{ inputs.meteor_version }}


